### ISSUE TITLE
Delete example csv files

### ISSUE THREAD

**Issue by birgits** [wind-python/windpowerlib#73]
Example csv files in example/data are unnecessary now as the oedb csv files are provided along with the windpowerlib. The examples and documentation need to be adapted accordingly.

**Comment by birgits** [comment]
In this course we should also revise the paths to the csv files in the examples. Right now when downloading the examples it is quite confusing where the files should be stored... The easiest would be to just have them in the same directory as the example file.

**Comment by uvchik** [comment]
> The easiest would be to just have them in the same directory as the example file.

:+1:  I agree as the weather.csv file is already there.

> Furthermore, it would be nice to have download links for the examples and data files in the README analogue to the download links in the getting_started if that's possible.

It is possible but you have to download every single file separately.

Alternatively we could host a zip-file with all examples somewhere else (e.g. osf) and provide a download link to the zip file including all examples and data files.

**Comment by vezeli** [comment]
@birgits @uvchik  I like it the way it is now with weather.csv file (consider that I am a newcomer and I went recently though the examples with zero knowledge of windpowerlib).

> Alternatively we could host a zip-file with all examples somewhere else (e.g. osf) and provide one download link to the zip file including all examples and data files.

Sorry @uvchik but IMHO this sounds clunky. Don't expect new-coming users to read and follow links to find zipped files. This process should be as simple as possible so that users would (at least) give a try to windpowerlib.

Setting up https://mybinder.org/ would be a perfect one-click solution for this problem. If you are unfamiliar here is a sum-up. Setting up binder would make possible to click on a link (in a form of a badge) in README.rst and this would set up windpowerlib inside a virtual environment on cloud. There, in the cloud, the users can test all .ipynb example files without cloning, downloading or unzipping the project.

Few days ago, I was curious so I set up binder together with [wind-python/windpowerlib](https://github.com/wind-python/windpowerlib) and it seemed to be working. I don't know how interested you are in doing this but I think I could reconstruct it easily and make a PR? I believe it will make windpowerlib more appealing for the new-coming users that just want to see how windpowerlib works. What do you think?

**Comment by uvchik** [comment]
In my opinion "download and unpack" is not too difficult but I have no strong feelings about that.

As we just have one data file left we do not need a zip file any more. People could just download two files in the same folder and execute the python file.

A third variant would be to download the weather file automatically. As the `'requests` package is already part of the requirements this would not lead to additional packages. One would start the example script and on the first run the weather file would be downloaded. Pretty simple.

@vezeli I do not know anything about mybinder, but if you think this is a good idea, go ahead :+1:

**Comment by SabineHaas** [comment]
oemof dev
decisions about examples in general:
- executable juptyer notebooks
- reduced python scripts
- automatic download of weather.csv in example

**Comment by uvchik** [comment]
I opened a new issue with the two and three of the list above. If you are aware of the notebooks we can close this issue.

**Comment by uvchik** [comment]
I revised the examples and added code to download the weather data.

@birgits Could you please adapt the Notebooks?
