### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vezeli** [wind-python/windpowerlib#82]
There is a broken link in [windpowerlib/wind_turbine.py#L489](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/wind_turbine.py#L489).

**Comment by Ludee** [comment]
Thanks @vezeli 
The **wind turbine library** has been moved:
https://openenergy-platform.org/dataedit/view/supply/wind_turbine_library

**Comment by vezeli** [comment]
Oh cool! @Ludee want me to make a PR to change it?

**Comment by Ludee** [comment]
Yes, please go ahead if you are familiar with branching and PR.

**Comment by SuperKogito** [comment]
I think broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.

**Comment by vezeli** [comment]
@SuperKogito You have a point about running automated checks for broken links (automated check was what revealed this broken link in the first place).

Sphinx is already equipped with a tool for checking external links. Running ``sphinx-build`` in CI together with [builder](https://www.sphinx-doc.org/en/master/man/sphinx-build.html?highlight=linkcheck) ``-b linkcheck`` option and an option to turn warnings into errors ``-W` does the same job.

**Comment by SuperKogito** [comment]
Yes, you are right about Sphinx. Indeed sphinx provides this feature but it only covers the docs (`.rst` files as far as I know). However, the action I wrote also covers links in `.md` files and even code such as `.py` files.
