### ISSUE TITLE
Upcoming release v0.2.1

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#99]
In April I would like to release the v0.2.1. There are already some small fixes and improvements and hopefully we can complete the issues we planned to do at the developer meeting (I changed the milestones from dev-meeting to v0.2.1).

So we will have a new release at the dev meeting in May :smile: 

![GitHub commits since tagged version (branch)](https://img.shields.io/github/commits-since/wind-python/windpowerlib/v0.2.0/dev)

**Comment by uvchik** [comment]
I think we do not have to stick to the date but I think we should at least update the examples.

**Comment by birgits** [comment]
At the dev meeting we decided to release soon (aimed at date is May 28) in order to provide newly added functionalities that are already in the documentation to the users. All open issues are more or less nice to have. @uvchik will try to complete PR #101 as it is crucial for smooth working of the windpowerlib.

**Comment by p-snft** [comment]
By now, this is overdue by almost a year. Especially the upper limit for the dependencies is an issue that can render the package unusable.

**Comment by uvchik** [comment]
![GitHub commits since tagged version (branch)](https://img.shields.io/github/commits-since/wind-python/windpowerlib/v0.2.0/dev)

I agree. We should release soon. I will see if I will be able to do it this week.

**Comment by uvchik** [comment]
Done
